docker build ./service-discovery -t servicediscovery
docker build ./api-gateway -t apigateway
docker build ./config-server -t configserver
docker build ./EventService -t eventservice
docker build ./JobService -t jobservice
docker build ./user-service -t userservice
docker build ./insight -t insights
docker build ./NewsAndAnnouncements -t newsannouncements
docker build ./Survey -t survey
docker build ./chat-service -t chatservice