version: '3'
services:
  api-gateway:
    container_name: api-gateway
    image: api-gateway-image:1.0
    ports:
      - "8080:8080"
    depends_on:
      - configuration-service
      - service-discovery
    networks:
      - ea_bridge

  configuration-service:
    container_name: configuration-service
    image: saikhanbat/configuration-service-image:first-image
    ports:
      - "9876:9876"
    depends_on:
      - service-discovery
    networks:
      - ea_bridge
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9876/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  service-discovery:
    container_name: service-discovery
    image: saikhanbat/service-discovery-image:first-image
    ports:
      - "8761:8761"
    networks:
      - ea_bridge

  job-service:
    container_name: job-service
    image: job-service-image:1.0
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - job-sql
      - configuration-service
    networks:
      - ea_bridge

  user-service:
    container_name: user-service
    image: saikhanbat/user-service-image:first-image
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - user-sql
      - configuration-service
    networks:
      - ea_bridge

  user-sql:
    container_name: user-sql
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: Grimmyreaper0621*
      MYSQL_DATABASE: alumni-user-db
    ports:
      - "3306:3306"
    networks:
      - ea_bridge

  job-sql:
    container_name: job-sql
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: Grimmyreaper0621*
      MYSQL_DATABASE: alumni-job-db
    ports:
      - "3307:3306"
    networks:
      - ea_bridge

networks:
  ea_bridge:
    driver: bridge