spring:
  application:
    name: api-gateway-service
  config:
    import: optional:configserver:http://configuration-service:9876
  cloud:
    gateway:
      routes:
        - id: userService
          uri: http://user-service:8082
          predicates:
            - Path=/users/**
#          filters:
#            - name: CustomHeader

        - id: jobService
          uri: http://job-service:8081
          predicates:
            - Path=/jobs/**
#          filters:
#            - name: CustomHeader

eureka:
  client:
    service-url:
      default-zone: http://service-discovery:8761/eureka

server:
  port: 8080



