FROM eclipse-temurin:17

LABEL maintainer="dunkygeoffrey39@gmail.com"

WORKDIR /home/app

COPY target/springboot-course-service-0.0.1-SNAPSHOT.jar /home/app/restful-course-service1.jar

ENTRYPOINT ["java", "-jar", "restful-course-service1"]